### ISSUE TITLE
Issue with platforms

### ISSUE THREAD

**Issue by romainsacchi** [amauryval/publish_conda_package_action#3]
Hello,

I am having the following issue:

```
+ read file
+ find temp_build/ -name '*.tar.bz2'
+ echo temp_build/noarch/premise-0.4.2-0.tar.bz2
+ for PLATFORM in "${PLATFORMS[@]}"
temp_build/noarch/premise-0.4.2-0.tar.bz2
+ conda convert --force --platform osx-64 temp_build/noarch/premise-0.4.2-0.tar.bz2 -o temp_build/
Traceback (most recent call last):
  File "/opt/conda/bin/conda-convert", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_convert.py", line 131, in main
    return execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_convert.py", line 127, in execute
    api.convert(f, **args.__dict__)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 300, in convert
    dry_run=dry_run, dependencies=dependencies)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/convert.py", line 763, in conda_convert
    conversion_platform, source_platform, architecture = retrieve_package_platform(file_path)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/convert.py", line 69, in retrieve_package_platform
    if platform.startswith('linux') or platform.startswith('osx'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

when using:

```
- name: Publish distribution 📦 to Anaconda if Push
        uses: amauryval/publish_conda_package_action@1.1.0
        with:
          # CondaDir: locate the directory containing your meta.yml, conda_build_config.yaml (...) files
          CondaDir: 'conda'
          # Channels: You can add more channel with a space separator
          Channels: 'conda-forge'
          # Platforms: remove one or more of these platforms
          Platforms: 'osx-64 linux-32 linux-64 win-32 win-64'
          CondaUsername: ${{ secrets.CONDA_USERNAME }}
          CondaPassword: ${{ secrets.CONDA_PASSWORD }}
```

Should I modify the list of platforms?

Thanks.

**Comment by romainsacchi** [comment]
For information, I tried with:

`Platforms: 'win-64'` and also without the 'Platforms' argument, the result is the same.

And my conda meta.yaml is [here](https://github.com/romainsacchi/premise/blob/master/conda/meta.yaml).

**Comment by amauryval** [comment]
Hello, 
Your configuration looks like good.
All your librairies can be found on conda? Dependencies issues?

**Comment by romainsacchi** [comment]
Not that I could see.
Finally, I resorted to writing a conda script for the upload.
If no one had that error before me, the issue was probably on my end.
Thanks for the help anyway.
